#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6444498429                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : be                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Weather Along The Way.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Senne Scheepers                                
your_link                                 : https://www.linkedin.com/in/sennescheepers/                     
your_city                                 :                                 
email_address                             : senne.scheepers@gmail.com
facebook_username                         :                                           
instagram_username                        : sennescheepers
twitter_username                          : 
github_username                           : sennescheepers
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track your bikes
    description                           : Keep track of all your bikes in an easy way.
    fontawesome_icon_name                 : bicycle
    
  - title                                 : Dynamic components
    description                           : Easily assign components to bikes, or even swap them out when you need to.
    fontawesome_icon_name                 : cog

  - title                                 : Mileage tracking
    description                           : Track the mileage on every bike and component individually. Stay on top of maintentance and get insights in the lifespan of your favorite products.
    fontawesome_icon_name                 : tachometer-alt

  - title                                 : Link with Strava
    description                           : Don't bother manually logging your rides. Connect the app with Strava and get notified when there's a new ride waiting to be logged to one of your bikes.
    fontawesome_icon_name                 : fa-strava

  # - title                                 : Maintenance intervals
  #   description                           : Setup maintenance intervals for your bikes and components and get notified when it's time for a service or upgrade.
  #   fontawesome_icon_name                 : timer

  # - title                                 : Widgets
  #   description                           : Keep an eye on your bike straight from your homepage.
  #   fontawesome_icon_name                 : mobile



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#007AFF"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#007AFF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
